export type ShopifyProduct = {
    available: boolean;
    category: Record<string, any>;
    collections: any[];
    compare_at_price: string;
    compare_at_price_max: string;
    compare_at_price_min: string;
    compare_at_price_varies: boolean;
    content: string;
    created_at: string;
    description: string;
    featured_image: Record<string, any>;
    featured_media: Record<string, any>;
    first_available_variant: Record<string, any>;
    gift_card: boolean;
    handle: string;
    has_only_default_variant: boolean;
    id: number;
    images: any[];
    media: any[];
    metafields: Record<string, any>;
    options: string[];
    options_by_name: Record<string, any>;
    options_with_values: any[];
    price: string;
    price_max: string;
    price_min: string;
    price_varies: boolean;
    published_at: string;
    quantity_price_breaks_configured: boolean;
    requires_selling_plan: boolean;
    selected_or_first_available_selling_plan_allocation: Record<string, any>;
    selected_or_first_available_variant: Record<string, any>;
    selected_selling_plan: any | null;
    selected_selling_plan_allocation: any | null;
    selected_variant: any | null;
    selling_plan_groups: any[];
    tags: string[];
    template_suffix: string;
    title: string;
    type: Record<string, any>;
    url: Record<string, any>;
    variants: any[];
    vendor: string;
};
